- docs/UserGuide.md
Added v1.2 unofficial draft. Individual team members to polish the features they are in charge of
> Update UserGuide with V1.2 features

- docs/DeveloperGuide.md
Based on project notes from previous weeks
> Update DeveloperGuide with base requirements

- docs/_config.yml
Closes #34
- Update site's header name
- Update header github link to point to teams' repo
> Update sitewide configs

- README.md
Closes #33 
Updates made:
- Github actions url
- CI status reference
- Description of the application
- Link to product webpage
> Update README to reflect PharmHub project

- docs/UserGuide.md
> [UG] Update all AddressBook occurrence with PharmHub

- docs/DeveloperGuide.md
> [DG] Add a use case and NFR

- README.md
- docs/index.md
Updates Made:
- ReadMe to include Welcome message
- Index CI to refer to Pharmhub
- Index content to Pharmhub
> Update ReadMe content and Index to refer to Pharmhub

- src/main/java/seedu/address/logic/commands/AddOrderCommand.java
- src/main/java/seedu/address/logic/parser/AddOrderCommandParser.java
- src/main/java/seedu/address/logic/parser/AddressBookParser.java
- src/main/java/seedu/address/logic/parser/CliSyntax.java
- src/main/java/seedu/address/model/AddressBook.java
- src/main/java/seedu/address/model/Model.java
- src/main/java/seedu/address/model/ModelManager.java
- src/main/java/seedu/address/model/ReadOnlyAddressBook.java
- src/main/java/seedu/address/model/order/Order.java
- src/main/java/seedu/address/model/order/OrderList.java
- src/main/java/seedu/address/storage/JsonAdaptedOrder.java
- src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
- src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
- src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
- src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
- src/test/java/seedu/address/logic/commands/AddCommandTest.java
- src/test/java/seedu/address/logic/commands/AddOrderCommandTest.java
- src/test/java/seedu/address/logic/parser/AddOrderCommandParserTest.java
- src/test/java/seedu/address/model/AddressBookTest.java
- src/test/java/seedu/address/model/order/OrderListTest.java
- src/test/java/seedu/address/model/order/OrderTest.java
- src/test/java/seedu/address/testutil/TypicalOrders.java
- src/test/java/seedu/address/testutil/TypicalPersons.java
> Update model to support order

- src/main/java/seedu/address/logic/commands/AddOrderCommand.java
- src/main/java/seedu/address/logic/parser/AddOrderCommandParser.java
- src/main/java/seedu/address/logic/parser/AddressBookParser.java
- src/main/java/seedu/address/logic/parser/CliSyntax.java
- src/main/java/seedu/address/model/AddressBook.java
- src/main/java/seedu/address/model/Model.java
- src/main/java/seedu/address/model/ModelManager.java
- src/main/java/seedu/address/model/ReadOnlyAddressBook.java
- src/main/java/seedu/address/model/order/Order.java
- src/main/java/seedu/address/model/order/OrderList.java
- src/main/java/seedu/address/storage/JsonAdaptedOrder.java
- src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
- src/main/java/seedu/address/ui/MainWindow.java
- src/main/java/seedu/address/ui/OrderDisplay.java
- src/main/resources/view/DarkTheme.css
- src/main/resources/view/MainWindow.fxml
- src/main/resources/view/OrderDisplay.fxml
- src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
- src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
- src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
- src/test/java/seedu/address/logic/commands/AddCommandTest.java
- src/test/java/seedu/address/logic/commands/AddOrderCommandTest.java
- src/test/java/seedu/address/logic/parser/AddOrderCommandParserTest.java
- src/test/java/seedu/address/model/AddressBookTest.java
- src/test/java/seedu/address/model/order/OrderListTest.java
- src/test/java/seedu/address/model/order/OrderTest.java
- src/test/java/seedu/address/testutil/TypicalOrders.java
- src/test/java/seedu/address/testutil/TypicalPersons.java
Closes #30 
Things added or changed:
- Added a OrderDisplay under Ui
- Added a OrderDiaplay FXML under resources/view
- Added OrderDisplay into MainWindow 
- Updated MainWindow application title to PharmHub
> Add new Order Display for UI and in FXML

- src/main/java/seedu/address/logic/commands/CommandResult.java
- src/main/java/seedu/address/logic/commands/ViewOrderCommand.java
- src/main/java/seedu/address/logic/parser/AddressBookParser.java
- src/main/java/seedu/address/logic/parser/ViewOrderCommandParser.java
- src/main/java/seedu/address/model/AddressBook.java
- src/main/java/seedu/address/model/InfoObject.java
- src/main/java/seedu/address/model/Model.java
- src/main/java/seedu/address/model/ModelManager.java
- src/main/java/seedu/address/model/ReadOnlyAddressBook.java
- src/main/java/seedu/address/model/order/Order.java
- src/main/java/seedu/address/model/order/OrderList.java
- src/main/java/seedu/address/ui/MainWindow.java
- src/main/java/seedu/address/ui/OrderDisplay.java
- src/main/resources/view/MainWindow.fxml
- src/test/java/seedu/address/logic/commands/AddCommandTest.java
- src/test/java/seedu/address/logic/commands/CommandResultTest.java
- src/test/java/seedu/address/logic/commands/ViewOrderCommandTest.java
- src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
- src/test/java/seedu/address/logic/parser/ViewOrderCommandParserTest.java
- src/test/java/seedu/address/model/AddressBookTest.java
- src/test/java/seedu/address/testutil/TypicalOrders.java
Changes to note:
- CommandResult now has yet another attribute, InfoObject, which is an interface for any object we would like to display on the info panel. There is potential to extend this for Person too, by simply having Person implement InfoObject.
Closes #4
> Create vieworder feature

- docs/UserGuide.md
> UG: Update listo and listp

- src/main/java/seedu/address/ui/OrderDisplay.java
- src/main/resources/view/OrderDisplay.fxml
Closes #4 
Updates made:
- Updated the display to show the order number, name and medication of the order.
> Update order display panel to show the details of the order

- docs/UserGuide.md
> docs: update UG for allergies functionality

- src/main/java/seedu/address/logic/Messages.java
- src/main/java/seedu/address/logic/commands/AddOrderCommand.java
- src/main/java/seedu/address/logic/parser/AddOrderCommandParser.java
- src/main/java/seedu/address/logic/parser/CliSyntax.java
- src/main/java/seedu/address/model/person/Person.java
- src/test/java/seedu/address/logic/commands/AddOrderCommandTest.java
- src/test/java/seedu/address/logic/parser/AddOrderCommandParserTest.java
- src/test/java/seedu/address/model/person/PersonTest.java
> Add warning when adding an order that a patient is allergic to

- docs/DeveloperGuide.md
> DG: Create listo draft

- docs/DeveloperGuide.md
> DG: Add Use Case for updating order status

- src/main/java/seedu/address/commons/util/StringUtil.java
- src/main/java/seedu/address/logic/commands/ViewPersonCommand.java
- src/main/java/seedu/address/logic/parser/AddressBookParser.java
- src/main/java/seedu/address/logic/parser/ViewPersonCommandParser.java
- src/main/java/seedu/address/model/person/Person.java
- src/main/java/seedu/address/ui/MainWindow.java
- src/main/java/seedu/address/ui/PersonDisplay.java
- src/main/resources/view/PersonDisplay.fxml
- src/test/java/seedu/address/commons/util/StringUtilTest.java
- src/test/java/seedu/address/logic/commands/ViewPersonCommandTest.java
- src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
- src/test/java/seedu/address/logic/parser/ViewPersonCommandParserTest.java
> Feature: ViewPerson

- src/main/java/seedu/address/logic/commands/AddOrderCommand.java
- src/main/java/seedu/address/logic/commands/ViewOrderCommand.java
- src/main/java/seedu/address/logic/parser/AddOrderCommandParser.java
- src/main/java/seedu/address/logic/parser/ParserUtil.java
- src/main/java/seedu/address/logic/parser/ViewOrderCommandParser.java
- src/main/java/seedu/address/model/AddressBook.java
- src/main/java/seedu/address/model/Model.java
- src/main/java/seedu/address/model/ModelManager.java
- src/main/java/seedu/address/model/ReadOnlyAddressBook.java
- src/main/java/seedu/address/model/order/Order.java
- src/main/java/seedu/address/model/order/OrderList.java
- src/main/java/seedu/address/model/order/OrderNumber.java
- src/main/java/seedu/address/model/order/exceptions/DuplicateOrderException.java
- src/main/java/seedu/address/storage/JsonAdaptedOrder.java
- src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
- src/main/java/seedu/address/ui/OrderDisplay.java
- src/test/data/JsonSerializableAddressBookTest/duplicateOrderAddressBook.json
- src/test/data/JsonSerializableAddressBookTest/invalidOrderPersonAddressBook.json
- src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
- src/test/java/seedu/address/logic/commands/AddCommandTest.java
- src/test/java/seedu/address/logic/commands/AddOrderCommandTest.java
- src/test/java/seedu/address/logic/commands/ViewOrderCommandTest.java
- src/test/java/seedu/address/logic/parser/AddOrderCommandParserTest.java
- src/test/java/seedu/address/logic/parser/ViewOrderCommandParserTest.java
- src/test/java/seedu/address/model/AddressBookTest.java
- src/test/java/seedu/address/model/order/OrderListTest.java
- src/test/java/seedu/address/model/order/OrderTest.java
- src/test/java/seedu/address/storage/JsonAdaptedOrderTest.java
- src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
- src/test/java/seedu/address/testutil/TypicalOrders.java
Order number is a integer and deleting or editing a person doesn't affect the orders associated with the person.
Let's change that by deleting and editing orders that belong to person when that person is deleted or edited.
Let's also make orderNumber into a class
Closes #67
> Fix order 

- src/main/java/seedu/address/logic/Messages.java
- src/main/java/seedu/address/logic/commands/AddOrderCommand.java
- src/main/java/seedu/address/logic/commands/UpdateStatusCommand.java
- src/main/java/seedu/address/logic/parser/AddOrderCommandParser.java
- src/main/java/seedu/address/logic/parser/ParserUtil.java
- src/main/java/seedu/address/model/order/Order.java
- src/main/java/seedu/address/model/order/OrderList.java
- src/main/java/seedu/address/model/person/Person.java
- src/main/java/seedu/address/storage/JsonAdaptedOrder.java
- src/main/java/seedu/address/ui/OrderCard.java
- src/main/java/seedu/address/ui/OrderDisplay.java
- src/main/resources/view/DarkTheme.css
- src/main/resources/view/OrderListCard.fxml
- src/test/data/JsonSerializableAddressBookTest/duplicateOrderAddressBook.json
- src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
- src/test/data/JsonSerializableAddressBookTest/invalidOrderPersonAddressBook.json
- src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
- src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
- src/test/java/seedu/address/logic/commands/AddOrderCommandTest.java
- src/test/java/seedu/address/logic/parser/AddOrderCommandParserTest.java
- src/test/java/seedu/address/model/AddressBookTest.java
- src/test/java/seedu/address/model/order/OrderListTest.java
- src/test/java/seedu/address/model/order/OrderTest.java
- src/test/java/seedu/address/storage/JsonAdaptedOrderTest.java
- src/test/java/seedu/address/testutil/EditOrderDescriptorBuilder.java
- src/test/java/seedu/address/testutil/OrderBuilder.java
- src/test/java/seedu/address/testutil/TypicalOrders.java
> Feature: Allow multiple medicines

- src/main/java/seedu/address/ui/OrderDisplay.java
- src/main/resources/view/OrderDisplay.fxml
closes #95 
Updates Made:
- Removed underline
- Added status for orderdisplay
> Update vieworder display to show status

- src/main/java/seedu/address/logic/Logic.java
- src/main/java/seedu/address/logic/LogicManager.java
- src/main/java/seedu/address/logic/Messages.java
- src/main/java/seedu/address/logic/commands/CommandResult.java
- src/main/java/seedu/address/logic/commands/FindMedicineCommand.java
- src/main/java/seedu/address/logic/commands/ListMedicineCommand.java
- src/main/java/seedu/address/logic/parser/AddressBookParser.java
- src/main/java/seedu/address/logic/parser/FindMedicineCommandParser.java
- src/main/java/seedu/address/ui/MainWindow.java
- src/main/java/seedu/address/ui/MedicineCard.java
- src/main/java/seedu/address/ui/MedicineListPanel.java
- src/main/java/seedu/address/ui/OrderCard.java
- src/main/resources/view/DarkTheme.css
- src/main/resources/view/MedicineListCard.fxml
- src/main/resources/view/MedicineListPanel.fxml
- src/test/java/seedu/address/logic/commands/CommandTestUtil.java
- src/test/java/seedu/address/logic/commands/FindMedicineCommandTest.java
- src/test/java/seedu/address/logic/commands/ListMedicineCommandTest.java
- src/test/java/seedu/address/logic/parser/FindMedicineCommandParserTest.java
- src/test/java/seedu/address/testutil/TypicalOrders.java
find medicine finds medicine if any of the given keywords is a substring of the medicine name (case insensitive) as opposed to findperson which matches on a word basis
> List and find medicine

- src/main/java/seedu/address/logic/commands/UpdateStatusCommand.java
- src/main/java/seedu/address/logic/parser/UpdateStatusCommandParser.java
- src/main/java/seedu/address/model/order/Status.java
- src/test/java/seedu/address/logic/commands/UpdateStatusCommandTest.java
- src/test/java/seedu/address/logic/parser/UpdateStatusCommandParserTest.java
closes #94 
Updates made:
- Add chronological order for status
- Add Short form for Order status
- Add test cases
> Add chronological status and short form for order status

- src/main/java/seedu/address/logic/commands/AddPersonCommand.java
- src/main/java/seedu/address/logic/commands/EditPersonCommand.java
- src/main/java/seedu/address/logic/parser/AddPersonCommandParser.java
- src/main/java/seedu/address/model/AddressBook.java
- src/main/java/seedu/address/model/person/Person.java
- src/main/java/seedu/address/model/person/UniquePersonList.java
- src/main/java/seedu/address/model/util/SampleDataUtil.java
- src/main/java/seedu/address/storage/JsonAdaptedPerson.java
- src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
- src/main/java/seedu/address/ui/PersonDisplay.java
- src/main/java/seedu/address/ui/PersonDisplayOrderCard.java
- src/main/resources/view/DarkTheme.css
- src/main/resources/view/PersonDisplay.fxml
- src/main/resources/view/PersonDisplayOrderListCard.fxml
- src/test/java/seedu/address/testutil/PersonBuilder.java
> Feature: Create an orderlist in Viewperson

- src/main/java/seedu/address/logic/Messages.java
- src/main/java/seedu/address/logic/commands/RedoCommand.java
- src/main/java/seedu/address/logic/commands/UndoCommand.java
- src/main/java/seedu/address/logic/parser/AddressBookParser.java
- src/main/java/seedu/address/model/Model.java
- src/main/java/seedu/address/model/ModelManager.java
- src/main/java/seedu/address/model/VersionedAddressBook.java
- src/test/java/seedu/address/logic/commands/AddPersonCommandTest.java
> Feature: undo/redo

- src/main/java/seedu/address/logic/commands/AddShortFormCommand.java
- src/main/java/seedu/address/logic/parser/AddShortFormCommandParser.java
- src/main/java/seedu/address/logic/parser/CliSyntax.java
Change addsfm to sfm
d/ flag deletes the shortform
> Branch update sfm

- src/main/java/seedu/address/model/person/Name.java
> Update name regex

- src/main/java/seedu/address/logic/Messages.java
- src/main/java/seedu/address/logic/commands/EditPersonCommand.java
- src/main/java/seedu/address/logic/parser/EditPersonCommandParser.java
- src/main/java/seedu/address/model/person/Person.java
- src/test/java/seedu/address/logic/commands/EditPersonCommandTest.java
- src/test/java/seedu/address/logic/commands/UpdateStatusCommandTest.java
- src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
- src/test/java/seedu/address/logic/parser/EditPersonCommandParserTest.java
> Fix editp allergyorder bug

- src/main/java/seedu/address/logic/commands/ClearCommand.java
- src/main/java/seedu/address/model/AddressBook.java
- src/main/java/seedu/address/model/Model.java
- src/main/java/seedu/address/model/ModelManager.java
- src/main/java/seedu/address/model/VersionedAddressBook.java
- src/test/java/seedu/address/logic/commands/AddPersonCommandTest.java
> Fix: Undo clear command

- src/main/java/seedu/address/MainApp.java
- src/main/java/seedu/address/logic/commands/ClearCommand.java
- src/main/java/seedu/address/logic/commands/ExitCommand.java
- src/main/java/seedu/address/model/ModelManager.java
> Fix addressbook remains

- src/main/java/seedu/address/logic/parser/FindOrderCommandParser.java
- src/main/java/seedu/address/model/order/Status.java
- src/test/java/seedu/address/logic/commands/CommandTestUtil.java
- src/test/java/seedu/address/logic/parser/FindOrderCommandParserTest.java
- src/test/java/seedu/address/logic/parser/UpdateStatusCommandParserTest.java
Increase coverage
Updates made:
- Add test case for FindOrderCommandParser
> Add test case for FindOrderCommandParser

- src/main/java/seedu/address/model/AddressBook.java
- src/main/java/seedu/address/model/order/Order.java
- src/main/java/seedu/address/model/person/Person.java
Changes made:
Architecture of the model now works as such:
personList and orderList are the sources of truth for persons and orders respectively.
After every data modification, we will clear the orders in all persons and re-add the orders from orderlist into each respective person.
Closes #142 #159 #145
> Fix viewp and undo bugs

- docs/UserGuide.md
> docs: Add Examples to UG

- src/main/java/seedu/pharmhub/model/util/SampleDataUtil.java
Commit 2f2e44b4b2a9fb6517866d217531bbab3a652b74 from PR #209 modified sample data. It was later determined that this counts as a change in feature, hence this PR aims to undo the changes made in that pr
> Undo prior edits to sampledata
